### ISSUE TITLE
address the flask architecture in the steam life code

### ISSUE THREAD

**Issue by mohibm708** [Allen-ISD-Computer-Science/REPO_allencsforum.org_2024#13]
will either be replaced with normal html or i may use flask on the rest of the website? that might clash with the parts of the website made in react

**Comment by saip9** [comment]
@mohibm708 Please use Flask and don't replace it with normal html as it would break some pages in the STEAM Life website due to connection with the database and the routes that were specified in the **main.py** file. I have created a new issue #15 containing all the details about the STEAM Life Website. Please refer to that issue and let me know if you have any questions.

**Comment by mohibm708** [comment]
alright ill be working on steam_life in flask then : ]
